# Generated by Django 6.0.2 on 2026-02-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreed_to_terms',
            field=models.BooleanField(default=False),
        ),
    ]
