# Generated by Django 6.0.2 on 2026-02-14 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_user_agreed_to_terms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='agreed_to_terms',
            new_name='agree_to_terms',
        ),
    ]
